# Cade Williams

a.out:			main.cpp OrderedList.o OrderedList.h Student.o Student.h
				g++ main.cpp OrderedList.o Student.o
Student.o:		Student.cpp Student.h
				g++ -c Student.cpp -o Student.o
OrderedList.o:	OrderedList.cpp OrderedList.h
				g++ -c OrderedList.cpp -o OrderedList.o